### ISSUE TITLE
plugin is crashing and creating large files in some cases

### ISSUE THREAD

**Issue by bluntmess** [vikassandhu999/flutter_pdf_compressor#2]
Issue: Tried compressing the attached pdf file of size 20.7 MB (approx) but the resultant pdf size I got was 103MB (approx.). The pdf consists of 618 pages with images so I think the plugin is not working well with images.

Also, the plugin crashes sometimes when trying to process large pdf files like this.

Pdf file: [A17_FlightPlan.pdf](https://github.com/vikassandhu999/flutter_pdf_compressor/files/6564355/A17_FlightPlan.pdf)

Thanks.

**Comment by vikassandhu999** [comment]
Hi @brightseagit , thanks for notifying about the issue. Which Compress Quality level did you use to compress the provided pdf?
Can you try the CompressQuality.LOW?

`await PdfCompressor.compressPdfFile(inputFilePath, outputFilePath, CompressQuality.LOW);`

if still there is this issue i will try fix it ASAP.

Thanks

**Comment by bluntmess** [comment]
Thanks for your response. 
Yes, I used the example in your project with `CompressQuality.LOW`.

**Comment by vikassandhu999** [comment]
Hi @brightseagit , i have improved plugin for images. I tested it with the PDF you mentioned earlier and found some good results.
Here are the results with Different Compression Qualities : 
'LOW' : 20.7MB to 10.1MB &
'MEDIUM' :  20.7MB to 17.0MB

I hope this new update would help you.
Thanks

**Comment by bluntmess** [comment]
Hi, thanks for looking into it and making those changes, the plugin is working fine now.
